# Generated by Django 2.0.5 on 2018-05-25 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0002_auto_20180524_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='closest_mile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pct.HalfmileWaypoint'),
        ),
        migrations.AddField(
            model_name='location',
            name='closest_poi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pct.HalfmileWaypoint'),
        ),
        migrations.AddField(
            model_name='post',
            name='closest_mile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pct.HalfmileWaypoint'),
        ),
        migrations.AddField(
            model_name='post',
            name='closest_poi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pct.HalfmileWaypoint'),
        ),
    ]
