# Generated by Django 2.0.6 on 2018-06-21 00:34

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0004_gallery_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breadcrumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_id', models.BigIntegerField(unique=True)),
                ('timestamp', models.DateTimeField()),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('raw', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
