# Generated by Django 2.0.6 on 2018-06-21 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0005_breadcrumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadcrumb',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breadcrumbs', to='pct.Location'),
        ),
    ]
