# Generated by Django 2.0.6 on 2018-06-21 19:10

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0006_breadcrumb_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('url', models.URLField(max_length=500)),
                ('raw', django.contrib.postgres.fields.jsonb.JSONField()),
                ('closest_mile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pct.HalfmileWaypoint')),
                ('closest_poi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pct.HalfmileWaypoint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='closest_mile',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='closest_poi',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
