# Generated by Django 2.0.6 on 2018-07-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0008_auto_20180630_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='location_override',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='location',
            name='location_override',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='location_override',
            field=models.TextField(blank=True, default=''),
        ),
    ]
