# Generated by Django 2.0.6 on 2018-07-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0009_auto_20180701_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='instagram_id',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
