# Generated by Django 2.0.6 on 2018-07-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0010_instagrampost_instagram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='embed_html',
            field=models.TextField(blank=True),
        ),
    ]
