# Generated by Django 2.0.6 on 2018-07-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0011_instagrampost_embed_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='if this is blank, no individal url for the post will be available'),
        ),
    ]
