# Generated by Django 2.0.6 on 2018-07-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0012_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('miles_hiked', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='instagrampost',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp']},
        ),
    ]
