# Generated by Django 2.0.6 on 2018-07-02 14:02

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0013_auto_20180701_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='iNaturalistObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('location_override', models.TextField(blank=True, default='')),
                ('inaturalist_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(max_length=500)),
                ('raw', django.contrib.postgres.fields.jsonb.JSONField()),
                ('closest_mile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pct.HalfmileWaypoint')),
                ('closest_poi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pct.HalfmileWaypoint')),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='dailystats',
            options={'ordering': ['-date'], 'verbose_name_plural': 'daily stats'},
        ),
    ]
