# Generated by Django 2.0.7 on 2018-07-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0014_auto_20180702_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='inaturalistobservation',
            name='show_on_timeline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='show_on_timeline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='show_on_timeline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='show_on_timeline',
            field=models.BooleanField(default=True),
        ),
    ]
