# Generated by Django 2.0.7 on 2018-07-07 15:53

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0016_auto_20180704_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
