# Generated by Django 2.0.7 on 2018-07-07 15:54

from django.db import migrations


def turn_locations_into_posts(apps, schema_editor):
    Location = apps.get_model("pct", "location")
    Post = apps.get_model("pct", "post")

    for loc in Location.objects.all():
        data = {f.name: getattr(loc, f.name) for f in Location._meta.fields}
        del data["id"]
        Post.objects.create(**data)


class Migration(migrations.Migration):

    dependencies = [("pct", "0017_auto_20180707_1553")]

    operations = [migrations.RunPython(turn_locations_into_posts)]

