# Generated by Django 2.0.7 on 2018-07-07 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0018_auto_20180707_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='closest_mile',
        ),
        migrations.RemoveField(
            model_name='location',
            name='closest_poi',
        ),
        migrations.RemoveField(
            model_name='breadcrumb',
            name='location',
        ),
        migrations.AddField(
            model_name='breadcrumb',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breadcrumbs', to='pct.Post'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
