# Generated by Django 2.0.7 on 2018-07-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0019_auto_20180707_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='inaturalistobservation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
